import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Timeline of locking classic<Link href="/timeline">click to check</Link>
        </h1>
        <h1 className={styles.title}>
         Timeline of locking slider<Link href="/timelineSlider">click to check</Link>
        </h1>

       
      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}
